name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cargo build --verbose
        cargo build --release 
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: chaos-ntp
        path: |
          target/release/chaos-ntp
    - name: Run tests
      uses: actions-rs/tarpaulin@v0.1
      #run: cargo test --verbose
